name = "open-ucp"
main = "cloudflare/worker.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
UCP_NAME = "Nymrel Open UCP Edge Worker"
DEFAULT_NETWORK = "polygon"
DEFAULT_CURRENCY = "USD"
